from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(901, 664)
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget2.setGeometry(QtCore.QRect(10, 10, 881, 521))
        self.tableWidget2.setObjectName("tableWidget2")
        self.tableWidget2.setColumnCount(23)
        self.tableWidget2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(22, item)
        self.textBrowser2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser2.setGeometry(QtCore.QRect(10, 541, 881, 71))
        self.textBrowser2.setObjectName("textBrowser2")
        SecondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SecondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 26))
        self.menubar.setObjectName("menubar")
        SecondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SecondWindow)
        self.statusbar.setObjectName("statusbar")
        SecondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "Hissedar Ekranı"))
        item = self.tableWidget2.horizontalHeaderItem(0)
        item.setText(_translate("SecondWindow", "Adi"))
        item = self.tableWidget2.horizontalHeaderItem(1)
        item.setText(_translate("SecondWindow", "Soyadi"))
        item = self.tableWidget2.horizontalHeaderItem(2)
        item.setText(_translate("SecondWindow", "BabaAdi"))
        item = self.tableWidget2.horizontalHeaderItem(3)
        item.setText(_translate("SecondWindow", "TCKimlikNo"))
        item = self.tableWidget2.horizontalHeaderItem(4)
        item.setText(_translate("SecondWindow", "HissePay"))
        item = self.tableWidget2.horizontalHeaderItem(5)
        item.setText(_translate("SecondWindow", "HissePayda"))
        item = self.tableWidget2.horizontalHeaderItem(6)
        item.setText(_translate("SecondWindow", "EdinmeSebebi"))
        item = self.tableWidget2.horizontalHeaderItem(7)
        item.setText(_translate("SecondWindow", "Tarih"))
        item = self.tableWidget2.horizontalHeaderItem(8)
        item.setText(_translate("SecondWindow", "Yevmiye"))
        item = self.tableWidget2.horizontalHeaderItem(9)
        item.setText(_translate("SecondWindow", "Il"))
        item = self.tableWidget2.horizontalHeaderItem(10)
        item.setText(_translate("SecondWindow", "Ilce"))
        item = self.tableWidget2.horizontalHeaderItem(11)
        item.setText(_translate("SecondWindow", "MahalleKoyAdi"))
        item = self.tableWidget2.horizontalHeaderItem(12)
        item.setText(_translate("SecondWindow", "Ada"))
        item = self.tableWidget2.horizontalHeaderItem(13)
        item.setText(_translate("SecondWindow", "Parsel"))
        item = self.tableWidget2.horizontalHeaderItem(14)
        item.setText(_translate("SecondWindow", "PaftaNo"))
        item = self.tableWidget2.horizontalHeaderItem(15)
        item.setText(_translate("SecondWindow", "Mevkii"))
        item = self.tableWidget2.horizontalHeaderItem(16)
        item.setText(_translate("SecondWindow", "Yuzolcum"))
        item = self.tableWidget2.horizontalHeaderItem(17)
        item.setText(_translate("SecondWindow", "Cilt"))
        item = self.tableWidget2.horizontalHeaderItem(18)
        item.setText(_translate("SecondWindow", "Sayfa"))
        item = self.tableWidget2.horizontalHeaderItem(19)
        item.setText(_translate("SecondWindow", "AnaTasinmazNitelik"))
        item = self.tableWidget2.horizontalHeaderItem(20)
        item.setText(_translate("SecondWindow", "ArsaPay"))
        item = self.tableWidget2.horizontalHeaderItem(21)
        item.setText(_translate("SecondWindow", "ArsaPayda"))
        item = self.tableWidget2.horizontalHeaderItem(22)
        item.setText(_translate("SecondWindow", "BagimsizBolumNitelik"))

   
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
